version: '3.5'
services:
    web:
        environment:
            - DB_HOSTNAME=db
            - AUTH0_ENABLED=false
        container_name: dcsa_tnt
        build:
           .
        ports:
            - 9090:9090
        logging:
            options:
                max-file: '10'
                max-size: 200k

    db:
        container_name: dcsa_tnt_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        build:
            DCSA-Information-Model/datamodel/
        ports:
            - 5432:5432
