version: '3.5'

services:
    dcsa-tnt:
        build:
           .
        ports:
            - 9090:9090
        environment:
          - "db_hostname=dcsa-test-db"
          - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-nosecurity}"
          - "SPRING_DATASOURCE_PASSWORD=9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5"
          - "ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:-INFO}"
          - "DCSA_LOG_LEVEL=${DCSA_LOG_LEVEL:-INFO}"
        logging:
          options:
            max-file: '10'
            max-size: 200k

    dcsa-test-db:
        container_name: dcsa_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        build:
            DCSA-Information-Model/datamodel/
        ports:
            - 5432:5432

