dcsa:
  specification:
    version: 3.0.0

spring:
  application:
    name: DCSA-TNT
    context-path: /tnt/v3
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}/dcsa_tnt
    username: dcsa_db_owner
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  profiles:
    active: nosecurity
    group:
      dev: nosecurity, logsql, localdb
      test: nosecurity, logsql, localdb
      prod: default

server:
  port: 9090
  error:
    include-binding-errors: on_param
    include-message: always

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:INFO}
      dcsa: ${DCSA_LOG_LEVEL:INFO}

---
# A profile for disabling security
spring:
  config:
    activate:
      on-profile: nosecurity

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

---
# A profile for connecting to a local database
spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname:localhost}/dcsa_tnt
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5


---
# A profile for logging the sql generated by jpa
spring:
  config:
    activate:
      on-profile: logsql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
