name: DCSA-TNT DEV CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      STATUS: ${{ steps.healthcheck.outputs.STATUS }}
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Core", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "github", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'

      - name: Checkout dcsaorg/DCSA-Core
        uses: actions/checkout@v2.3.1
        with:
          repository: dcsaorg/DCSA-Core
          ref: dev-tnt
          path: DCSA-Core
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Set dcsa-core mvn version variable
        run: cd DCSA-Core && echo "DCSA_CORE_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)- " >> $GITHUB_ENV

      - run: echo $DCSA_CORE_PROJECT_VERSION

      - name: Checkout dcsaorg/DCSA-Event-Core
        uses: actions/checkout@v2.3.1
        with:
          repository: dcsaorg/DCSA-Event-Core
          ref: dev-tnt
          path: DCSA-Event-Core
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Set dcsa-event-core mvn version variable
        run: cd DCSA-Event-Core && echo "DCSA_EVENT_CORE_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)- " >> $GITHUB_ENV

      - run: echo $DCSA_EVENT_CORE_PROJECT_VERSION

      - name: Fetch backend
        uses: actions/checkout@v2
        with:
          path: DCSA-TNT
          submodules: recursive

      - name: Build TNT
        run: cd DCSA-TNT && mvn package -Ddcsa.version=$DCSA_CORE_PROJECT_VERSION -Ddcsa.core.tag=dev-tnt -Ddcsa.events.version=$DCSA_EVENT_CORE_PROJECT_VERSION -Ddcsa.event.tag=dev-tnt -Ddcsa.artifacttype=-SNAPSHOT

      - name: Build and run the microservices
        run: cd DCSA-TNT && docker-compose -f docker-compose.yml up -d -V

      - name: Fetch Backend Status
        run: |
          sleep 10
          echo "::set-output name=STATUS::$(curl -s http://localhost:9090/v2/actuator/health | jq -r '.status')"
        id: healthcheck

      - name: Confirm microservice status
        if: ${{ steps.healthcheck.outputs.STATUS == 'UP' }}
        run: |
            echo "The DCSA-TNT service is UP."

      - name: Confirm microservice status
        if: ${{ steps.healthcheck.outputs.STATUS != 'UP' }}
        uses: actions/github-script@v3
        with:
          script: |
           core.setFailed('The DCSA-TNT service is down.')